/*
ContextInitializer.m
Autogenerated by Subjective-C compiler.
*/
#import "contexts_10.h"
#import "ContextsInitializer.h"


@implementation ContextsInitializer

- (void)initializeContexts
{
    @synchronized([self class]) {
        if (alreadyInitialized) {
            return;
        }
        alreadyInitialized = YES;
    }
    // Contexts initialization
    SCContext *__Context1 = [[SCGlobalContext alloc] initWithName:@"Context1"]; 
[[SCContextManager sharedContextManager] addContext:__Context1]; 
SCContext *__Context2 = [[SCGlobalContext alloc] initWithName:@"Context2"]; 
[[SCContextManager sharedContextManager] addContext:__Context2]; 
SCContext *__Context3 = [[SCGlobalContext alloc] initWithName:@"Context3"]; 
[[SCContextManager sharedContextManager] addContext:__Context3]; 
SCContext *__Context4 = [[SCGlobalContext alloc] initWithName:@"Context4"]; 
[[SCContextManager sharedContextManager] addContext:__Context4]; 
SCContext *__Context5 = [[SCGlobalContext alloc] initWithName:@"Context5"]; 
[[SCContextManager sharedContextManager] addContext:__Context5]; 
SCContext *__Context6 = [[SCGlobalContext alloc] initWithName:@"Context6"]; 
[[SCContextManager sharedContextManager] addContext:__Context6]; 
SCContext *__Context7 = [[SCGlobalContext alloc] initWithName:@"Context7"]; 
[[SCContextManager sharedContextManager] addContext:__Context7]; 
SCContext *__Context8 = [[SCGlobalContext alloc] initWithName:@"Context8"]; 
[[SCContextManager sharedContextManager] addContext:__Context8]; 
SCContext *__Context9 = [[SCGlobalContext alloc] initWithName:@"Context9"]; 
[[SCContextManager sharedContextManager] addContext:__Context9]; 
SCContext *__Context10 = [[SCGlobalContext alloc] initWithName:@"Context10"]; 
[[SCContextManager sharedContextManager] addContext:__Context10]; 

    // Context methods registration
    

}

@end
