/*
ContextInitializer.m
Autogenerated by Subjective-C compiler.
*/
#import "contexts_50.h"
#import "ContextsInitializer.h"


@implementation ContextsInitializer

- (void)initializeContexts
{
    @synchronized([self class]) {
        if (alreadyInitialized) {
            return;
        }
        alreadyInitialized = YES;
    }
    // Contexts initialization
    SCContext *__Context1 = [[SCGlobalContext alloc] initWithName:@"Context1"]; 
[[SCContextManager sharedContextManager] addContext:__Context1]; 
SCContext *__Context2 = [[SCGlobalContext alloc] initWithName:@"Context2"]; 
[[SCContextManager sharedContextManager] addContext:__Context2]; 
SCContext *__Context3 = [[SCGlobalContext alloc] initWithName:@"Context3"]; 
[[SCContextManager sharedContextManager] addContext:__Context3]; 
SCContext *__Context4 = [[SCGlobalContext alloc] initWithName:@"Context4"]; 
[[SCContextManager sharedContextManager] addContext:__Context4]; 
SCContext *__Context5 = [[SCGlobalContext alloc] initWithName:@"Context5"]; 
[[SCContextManager sharedContextManager] addContext:__Context5]; 
SCContext *__Context6 = [[SCGlobalContext alloc] initWithName:@"Context6"]; 
[[SCContextManager sharedContextManager] addContext:__Context6]; 
SCContext *__Context7 = [[SCGlobalContext alloc] initWithName:@"Context7"]; 
[[SCContextManager sharedContextManager] addContext:__Context7]; 
SCContext *__Context8 = [[SCGlobalContext alloc] initWithName:@"Context8"]; 
[[SCContextManager sharedContextManager] addContext:__Context8]; 
SCContext *__Context9 = [[SCGlobalContext alloc] initWithName:@"Context9"]; 
[[SCContextManager sharedContextManager] addContext:__Context9]; 
SCContext *__Context10 = [[SCGlobalContext alloc] initWithName:@"Context10"]; 
[[SCContextManager sharedContextManager] addContext:__Context10]; 
SCContext *__Context11 = [[SCGlobalContext alloc] initWithName:@"Context11"]; 
[[SCContextManager sharedContextManager] addContext:__Context11]; 
SCContext *__Context12 = [[SCGlobalContext alloc] initWithName:@"Context12"]; 
[[SCContextManager sharedContextManager] addContext:__Context12]; 
SCContext *__Context13 = [[SCGlobalContext alloc] initWithName:@"Context13"]; 
[[SCContextManager sharedContextManager] addContext:__Context13]; 
SCContext *__Context14 = [[SCGlobalContext alloc] initWithName:@"Context14"]; 
[[SCContextManager sharedContextManager] addContext:__Context14]; 
SCContext *__Context15 = [[SCGlobalContext alloc] initWithName:@"Context15"]; 
[[SCContextManager sharedContextManager] addContext:__Context15]; 
SCContext *__Context16 = [[SCGlobalContext alloc] initWithName:@"Context16"]; 
[[SCContextManager sharedContextManager] addContext:__Context16]; 
SCContext *__Context17 = [[SCGlobalContext alloc] initWithName:@"Context17"]; 
[[SCContextManager sharedContextManager] addContext:__Context17]; 
SCContext *__Context18 = [[SCGlobalContext alloc] initWithName:@"Context18"]; 
[[SCContextManager sharedContextManager] addContext:__Context18]; 
SCContext *__Context19 = [[SCGlobalContext alloc] initWithName:@"Context19"]; 
[[SCContextManager sharedContextManager] addContext:__Context19]; 
SCContext *__Context20 = [[SCGlobalContext alloc] initWithName:@"Context20"]; 
[[SCContextManager sharedContextManager] addContext:__Context20]; 
SCContext *__Context21 = [[SCGlobalContext alloc] initWithName:@"Context21"]; 
[[SCContextManager sharedContextManager] addContext:__Context21]; 
SCContext *__Context22 = [[SCGlobalContext alloc] initWithName:@"Context22"]; 
[[SCContextManager sharedContextManager] addContext:__Context22]; 
SCContext *__Context23 = [[SCGlobalContext alloc] initWithName:@"Context23"]; 
[[SCContextManager sharedContextManager] addContext:__Context23]; 
SCContext *__Context24 = [[SCGlobalContext alloc] initWithName:@"Context24"]; 
[[SCContextManager sharedContextManager] addContext:__Context24]; 
SCContext *__Context25 = [[SCGlobalContext alloc] initWithName:@"Context25"]; 
[[SCContextManager sharedContextManager] addContext:__Context25]; 
SCContext *__Context26 = [[SCGlobalContext alloc] initWithName:@"Context26"]; 
[[SCContextManager sharedContextManager] addContext:__Context26]; 
SCContext *__Context27 = [[SCGlobalContext alloc] initWithName:@"Context27"]; 
[[SCContextManager sharedContextManager] addContext:__Context27]; 
SCContext *__Context28 = [[SCGlobalContext alloc] initWithName:@"Context28"]; 
[[SCContextManager sharedContextManager] addContext:__Context28]; 
SCContext *__Context29 = [[SCGlobalContext alloc] initWithName:@"Context29"]; 
[[SCContextManager sharedContextManager] addContext:__Context29]; 
SCContext *__Context30 = [[SCGlobalContext alloc] initWithName:@"Context30"]; 
[[SCContextManager sharedContextManager] addContext:__Context30]; 
SCContext *__Context31 = [[SCGlobalContext alloc] initWithName:@"Context31"]; 
[[SCContextManager sharedContextManager] addContext:__Context31]; 
SCContext *__Context32 = [[SCGlobalContext alloc] initWithName:@"Context32"]; 
[[SCContextManager sharedContextManager] addContext:__Context32]; 
SCContext *__Context33 = [[SCGlobalContext alloc] initWithName:@"Context33"]; 
[[SCContextManager sharedContextManager] addContext:__Context33]; 
SCContext *__Context34 = [[SCGlobalContext alloc] initWithName:@"Context34"]; 
[[SCContextManager sharedContextManager] addContext:__Context34]; 
SCContext *__Context35 = [[SCGlobalContext alloc] initWithName:@"Context35"]; 
[[SCContextManager sharedContextManager] addContext:__Context35]; 
SCContext *__Context36 = [[SCGlobalContext alloc] initWithName:@"Context36"]; 
[[SCContextManager sharedContextManager] addContext:__Context36]; 
SCContext *__Context37 = [[SCGlobalContext alloc] initWithName:@"Context37"]; 
[[SCContextManager sharedContextManager] addContext:__Context37]; 
SCContext *__Context38 = [[SCGlobalContext alloc] initWithName:@"Context38"]; 
[[SCContextManager sharedContextManager] addContext:__Context38]; 
SCContext *__Context39 = [[SCGlobalContext alloc] initWithName:@"Context39"]; 
[[SCContextManager sharedContextManager] addContext:__Context39]; 
SCContext *__Context40 = [[SCGlobalContext alloc] initWithName:@"Context40"]; 
[[SCContextManager sharedContextManager] addContext:__Context40]; 
SCContext *__Context41 = [[SCGlobalContext alloc] initWithName:@"Context41"]; 
[[SCContextManager sharedContextManager] addContext:__Context41]; 
SCContext *__Context42 = [[SCGlobalContext alloc] initWithName:@"Context42"]; 
[[SCContextManager sharedContextManager] addContext:__Context42]; 
SCContext *__Context43 = [[SCGlobalContext alloc] initWithName:@"Context43"]; 
[[SCContextManager sharedContextManager] addContext:__Context43]; 
SCContext *__Context44 = [[SCGlobalContext alloc] initWithName:@"Context44"]; 
[[SCContextManager sharedContextManager] addContext:__Context44]; 
SCContext *__Context45 = [[SCGlobalContext alloc] initWithName:@"Context45"]; 
[[SCContextManager sharedContextManager] addContext:__Context45]; 
SCContext *__Context46 = [[SCGlobalContext alloc] initWithName:@"Context46"]; 
[[SCContextManager sharedContextManager] addContext:__Context46]; 
SCContext *__Context47 = [[SCGlobalContext alloc] initWithName:@"Context47"]; 
[[SCContextManager sharedContextManager] addContext:__Context47]; 
SCContext *__Context48 = [[SCGlobalContext alloc] initWithName:@"Context48"]; 
[[SCContextManager sharedContextManager] addContext:__Context48]; 
SCContext *__Context49 = [[SCGlobalContext alloc] initWithName:@"Context49"]; 
[[SCContextManager sharedContextManager] addContext:__Context49]; 
SCContext *__Context50 = [[SCGlobalContext alloc] initWithName:@"Context50"]; 
[[SCContextManager sharedContextManager] addContext:__Context50]; 

    // Context methods registration
    // From source file /Users/NicolasCardozo/Documents/workspace-all/TassPaper/Subjective-C2/contexts_50/contexts_50/contexts_50.m
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context46_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context46, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context5_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context5, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context39_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context39, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context50_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context50, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context28_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context28, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context21_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context21, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context14_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context14, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context47_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context47, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context6_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context6, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context40_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context40, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context15_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context15, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context29_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context29, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context22_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context22, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context48_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context48, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context7_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context7, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context3_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context3, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context34_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context34, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context8_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context8, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context2_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context2, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context16_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context16, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context23_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context23, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context30_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context30, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context41_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context41, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context4_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context4, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context42_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context42, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context35_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context35, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context49_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context49, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context9_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context9, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context17_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context17, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context31_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context31, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context24_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context24, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context43_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context43, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context36_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context36, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context10_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context10, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context32_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context32, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context18_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context18, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context25_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context25, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context1_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context1, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context37_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context37, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context44_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context44, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context11_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context11, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context33_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context33, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context26_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context26, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context19_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context19, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context45_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context45, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context38_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context38, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context12_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context12, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context20_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context20, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context27_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context27, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];
[[SCMethodDispatcher sharedMethodDispatcher] addMethodWithSelector:@selector(Context_Context13_testS) fromRelatedClass:[Foo class] forContexts:[NSSet setWithObjects:__Context13, nil] withDefaultSelector:@selector(testS) priority:0 isInstance:YES];

}

@end
